FamousBlog_app/Categorys_app/urls.py
from django.urls import path
from . import views  # Переконайся, що views.py існує

app_name = "categorys"
urlpatterns = [
    path('', views.category_list, name='category_list'),
]

FamousBlog_app/Technology_app/urls.py
from django.urls import path
from . import views

app_name = "technology"

urlpatterns = [
    path('', views.index, name='index'),
]

FamousBlog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from FamousBlog_app.Blog_app import views as blog_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.home, name='home'),
    path('', include('FamousBlog_app.Autenfication_app.urls')),
    path('blog/', include('FamousBlog_app.Blog_app.urls')),
    path('advertisements/', include('FamousBlog_app.Advertisement_app.urls')),
    path('articles/', include('FamousBlog_app.Articles_app.urls')),
    path('categorys/', include('FamousBlog_app.Categorys_app.urls')),
    path('images/', include('FamousBlog_app.Image_app.urls')), 
    path('categorys/technologys/', include('FamousBlog_app.Technology_app.urls')),
    path('categorys/sports/', include('FamousBlog_app.Zal_app.urls')),
    path('categorys/paints/', include('FamousBlog_app.Art_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FamousBlog_app/Technology_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, "Technology_app/technic.html")

FamousBlog_app/Technology_app/templates/Technology_app/technic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h1 style="display: flex; justify-content: center; font-family: Impact; color: goldenrod;">Технології</h1> 
   <p style="margin-left: 72px; font-family: Impact;">Технологічна промисловість - це промисловість майбутнього.Вона є найбільш затребувана зараз із-за великого розвидку технологій які весь час оновлюються. </p>
  <div style="display: flex;justify-content: space-around; size: 150px;">
   <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1knxzIOrdcBTUYYu9DKM0LQ5tK18mmiTXYc2ihT2G&s" alt="">
   <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXlU9FHHeoxCyvNYZlIHuWwI4ShfLi3WqtJHPMveBB&s" alt=""
   >
   <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuOrbEYGgmFVjJBL_pyvyNFY6yNo2dsi6873dk7K0K&s" alt="">
   </div> 

<a  href="{% url 'categorys:category_list' %}" 
   class="btn-home" 
   style="background-color: lightgray; color: black; display: flex; justify-content: center; gap: 10px; margin-top: 15px;">
    ← Назад
</a>



</body>
</html>